version: '3'
services:
  web:
    build: ./docker/php
    volumes:
      - ./src:/var/www/html
    ports:
      - 8866:80
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 13306:3306
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: